openapi: 3.0.0
info:
  version: 1.0.0
  title: Authentication API
  description: API documentation for user authentication

servers:
  - url: http://localhost:3000/api

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
                phoneno:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: User registered successfully
        '400':
          description: User already exists
        '422':
          description: Validation error
        '500':
          description: Server error

  /api/auth/login:
    post:
      summary: Login a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Authentication failed
        '500':
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password_hash:
          type: string
        phoneno:
          type: string
        role:
          type: string

    Ticket:
      type: object
      properties:
        ticket_unique_identifier:
          type: string
        ticket_qr:
          type: string
        issue_time:
          type: string
          format: date-time
        expiry_time:
          type: string
          format: date-time
        trip_details:
          type: object
          properties:
            bus_id:
              type: integer
            source_stop_id:
              type: integer
            destination_stop_id:
              type: integer
            total_distance:
              type: number
            price_per_km:
              type: number
            no_of_passengers:
              type: integer
            fare:
              type: number
        is_valid:
          type: boolean
        user_id:
          type: integer
