openapi: 3.0.0
info:
  version: 1.0.0
  title: Auth API
  description: API documentation for authentication functionalities

servers:
  - url: http://localhost:3000/api

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        phoneno:
          type: string
        role:
          type: string

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: Password123
                confirm_password:
                  type: string
                  example: Password123
                phoneno:
                  type: string
                  example: 1234567890
                role:
                  type: string
                  example: passenger
      responses:
        '201':
          description: User registered successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: User registered successfully
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Validation error
                  errors:
                    type: array
                    items:
                      type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /auth/login:
    post:
      summary: User login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: Password123
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: your-jwt-token
        '401':
          description: Unauthorized, invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Invalid email or password
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error
