openapi: 3.0.0
info:
  version: 1.0.0
  title: Bus Route API
  description: API documentation for bus route functionalities

servers:
  - url: http://localhost:3000/api

components:
  schemas:
    City:
      type: object
      properties:
        city_id:
          type: integer
        city_name:
          type: string

    Stop:
      type: object
      properties:
        stop_id:
          type: integer
        stop_name:
          type: string

    Bus:
      type: object
      properties:
        bus_id:
          type: integer
        price_per_km:
          type: number
        total_distance:
          type: number
        fare:
          type: number

paths:
  /bus-route/city:
    get:
      summary: Get all cities
      tags:
        - Bus Route
      responses:
        '200':
          description: Successful response with city list
          content:
            application/json:
              schema:
                type: object
                properties:
                  city_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/City'
        '500':
          description: Server error

  /bus-route/city/{city_id}/source-stop:
    get:
      summary: Get all stops for a city
      tags:
        - Bus Route
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
          description: ID of the city
      responses:
        '200':
          description: Successful response with stop list
          content:
            application/json:
              schema:
                type: object
                properties:
                  source_stops:
                    type: array
                    items:
                      $ref: '#/components/schemas/Stop'
        '500':
          description: Server error

  /bus-route/city/{city_id}/source-stop/{source_id}/destination:
    get:
      summary: Get all possible destinations from a source stop
      tags:
        - Bus Route
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
          description: ID of the city
        - in: path
          name: source_id
          required: true
          schema:
            type: integer
          description: ID of the source stop
      responses:
        '200':
          description: Successful response with destination stop list
          content:
            application/json:
              schema:
                type: object
                properties:
                  destination_stop:
                    type: array
                    items:
                      $ref: '#/components/schemas/Stop'
        '500':
          description: Server error

  /bus-route/city/{city_id}/source-stop/{source_id}/destination/{destination_id}/bus:
    get:
      summary: Get bus list for chosen path
      tags:
        - Bus Route
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
          description: ID of the city
        - in: path
          name: source_id
          required: true
          schema:
            type: integer
          description: ID of the source stop
        - in: path
          name: destination_id
          required: true
          schema:
            type: integer
          description: ID of the destination stop
      responses:
        '200':
          description: Successful response with bus list
          content:
            application/json:
              schema:
                type: object
                properties:
                  bus_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Bus'
        '500':
          description: Server error
