openapi: 3.0.0
info:
  version: 1.0.0
  title: Bus Stop API
  description: API documentation for bus stop functionalities

servers:
  - url: http://localhost:3000/api

paths:
  /api/bus-route/city:
    get:
      summary: Get all cities
      tags:
        - Bus Stop
      responses:
        '200':
          description: Successful response
        '500':
          description: Server error

  /api/bus-route/city/{city_id}/source-stop:
    get:
      summary: Get all stops for a city
      tags:
        - Bus Stop
      parameters:
        - in: path
          name: city_id
          schema:
            type: integer
          required: true
          description: City ID
      responses:
        '200':
          description: Successful response
        '500':
          description: Server error

  /api/bus-route/city/{city_id}/source-stop/{source_id}/destination:
    get:
      summary: Get all possible destinations from a source stop
      tags:
        - Bus Stop
      parameters:
        - in: path
          name: city_id
          schema:
            type: integer
          required: true
          description: City ID
        - in: path
          name: source_id
          schema:
            type: integer
          required: true
          description: Source Stop ID
      responses:
        '200':
          description: Successful response
        '500':
          description: Server error

  /api/bus-route/city/{city_id}/source-stop/{source_id}/destination/{destination_id}/bus:
    get:
      summary: Get bus list for chosen path
      tags:
        - Bus Stop
      parameters:
        - in: path
          name: city_id
          schema:
            type: integer
          required: true
          description: City ID
        - in: path
          name: source_id
          schema:
            type: integer
          required: true
          description: Source Stop ID
        - in: path
          name: destination_id
          schema:
            type: integer
          required: true
          description: Destination Stop ID
      responses:
        '200':
          description: Successful response
        '500':
          description: Server error

components:
  schemas:
    City:
      type: object
      properties:
        city_id:
          type: integer
        city_name:
          type: string

    Stop:
      type: object
      properties:
        stop_id:
          type: integer
        stop_name:
          type: string

    Bus:
      type: object
      properties:
        bus_id:
          type: integer
        price_per_km:
          type: number
        total_distance:
          type: number
        fare:
          type: number
