openapi: 3.0.0
info:
  title: Conductor App
  version: 0.0.0
  description: This is the backend API for the Conductor App

paths:
  /api/bus-route/city:
    get:
      summary: Retrieve a list of cities
      description: Retrieve a list of all cities where bus stops are available.
      responses:
        '200':
          description: A list of cities
          content:
            application/json:
              schema:
                type: object
                properties:
                  city_list:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: New York
        '500':
          description: Unable to receive City List
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Unable to receive City List
                  error:
                    type: string
                    example: error details

  /api/bus-route/city/{city_id}/source-stop:
    get:
      summary: Retrieve all bus stops for a city
      description: Get a list of all bus stops for a given city.
      parameters:
        - name: city_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the city for which to retrieve bus stops.
      responses:
        '200':
          description: A list of bus stops in the specified city
          content:
            application/json:
              schema:
                type: object
                properties:
                  source_stops:
                    type: array
                    items:
                      type: object
                      properties:
                        stop_id:
                          type: integer
                          example: 1
                        stop_name:
                          type: string
                          example: Times Square
        '500':
          description: Unable to retrieve the list of bus stops
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Unable to receive City List
                  error:
                    type: string
                    example: Detailed error message

  /api/bus-route/city/{city_id}/source-stop/{source_id}/destination:
    get:
      summary: Get all possible destinations from a source stop
      description: Retrieve all possible destination stops from a given source stop for a specific city.
      parameters:
        - name: city_id
          in: path
          required: true
          description: The ID of the city.
          schema:
            type: string
        - name: source_id
          in: path
          required: true
          description: The ID of the source stop.
          schema:
            type: string
      responses:
        '200':
          description: A list of destination stops
          content:
            application/json:
              schema:
                type: object
                properties:
                  destination_stop:
                    type: array
                    items:
                      type: object
                      properties:
                        route_id:
                          type: string
                          description: The ID of the bus route.
                        stop_id:
                          type: string
                          description: The ID of the stop.
                        stop_name:
                          type: string
                          description: The name of the stop.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Unable to receive City List
                  error:
                    type: string
                    example: [Error details here]
