openapi: 3.0.0
info:
  version: 1.0.0
  title: Bus Route API
  description: API documentation for bus route functionalities

servers:
  - url: ${HOST_SERVER_URL}
  - url: http://localhost:3000/api

components:
  schemas:
    City:
      type: object
      properties:
        city_id:
          type: integer
        city_name:
          type: string

    Stop:
      type: object
      properties:
        stop_id:
          type: integer
        stop_name:
          type: string

    Bus:
      type: object
      properties:
        bus_id:
          type: integer
        price_per_km:
          type: number
        total_distance:
          type: number
        fare:
          type: number

paths:
  /bus-route/bus/{bus_id}:
    get:
      summary: Get stops from a bus ID
      tags:
        - Bus Route
      parameters:
        - in: path
          name: bus_id
          schema:
            type: integer
          required: true
          description: ID of the bus
          example: 1
      responses:
        '200':
          description: Successful response with bus stop details
          content:
            application/json:
              schema:
                type: object
                properties:
                  busStopsDetails:
                    type: array
                    items:
                      type: object
                      properties:
                        bus_id:
                          type: integer
                          example: 1
                        route_id:
                          type: integer
                          example: 101
                        stop_id:
                          type: integer
                          example: 1001
                        stop_name:
                          type: string
                          example: "Main Street"
                        stop_order:
                          type: integer
                          example: 1
                        distance_from_start:
                          type: number
                          example: 0.0
                        price:
                          type: number
                          example: 10.0
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Unable to receive Bus Stop info
                  error:
                    type: string
                    example: Internal Server Error
